<?php
/**
 * @package   Benabee_ProductManagerConnector
 * @author    Maxime Coudreuse <contact@benabee.com>
 * @copyright 2019 Benabee
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0).
 * @link      https://www.benabee.com/
 */

?>
<?php ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var generatekeySpan = jQuery('#generatekey_span');

        jQuery('#generatekey_button').click(function () {
            var params = {};

            new Ajax.Request('<?= $block->escapeUrl($block->getAjaxUrl()) ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    generatekeySpan.find('.generated').hide();
                    generatekeySpan.find('.processing').show();
                    jQuery('#generatekey_message_span').text('');
                },
                onSuccess: function(response) {
                    generatekeySpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        generatekeySpan.find('.generated').show();
                    }  

                    jQuery('#generatekey_message_span').text(resultText);
                    
                    var json = response.responseJSON;                   
                  
                    if (typeof json.key != 'undefined') {
                         jQuery('#product_manager_connector_configuration_security_key').val(json.key);
                    }
                }
            });
        });
    });
</script>

<?= $block->getButtonHtml() ?>
<span class="generatekey-indicator" id="generatekey_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <img class="generated" hidden="hidden" alt="generated" style="margin:-3px 5px" src="<?= $block->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"/>
    <span id="generatekey_message_span"></span>
</span>